### ISSUE TITLE
Please consider adding GitHub actions

### ISSUE THREAD

**Issue by ccoVeille** [sosodev/duration#11]
I'm thinking about

- launching test
- launching golangci-lint
- checking typos
- dependabot (mostly for keeping the GitHub actions up to date)

**Comment by sosodev** [comment]
Added by #10

**Comment by sosodev** [comment]
Note that I've just modified the branch protection for main to include passing checks too.

**Comment by ccoVeille** [comment]
Not exactly complete, golangci-lint was not added yet, or I missed something

**Comment by sosodev** [comment]
True. I've opened https://github.com/sosodev/duration/issues/12 to track the addition of linting.
