### ISSUE TITLE
Was release 1.3.0 ninja edited?

### ISSUE THREAD

**Issue by ghjm** [sosodev/duration#13]
I'm getting:

```
verifying github.com/sosodev/duration@v1.3.0: checksum mismatch
	downloaded: h1:g3E6mto+hFdA2uZXeNDYff8LYeg7v5D4YKP/Ng/NUkE=
	go.sum:     h1:tBpRC1/J04jBAXKnpF3V5Zqm0GVMQrIIOCOXEzME1Ks=
```

So either someone's attacking me, or the 1.3.0 release was re-published with changes to the files.  Can you shed any light on this?

**Comment by sosodev** [comment]
Hi, the original v1.3.0 was bugged so I did republish it. In hindsight I suppose I should have bumped the minor version instead. I think I'll do that now just to avoid this issue. Sorry about that.

**Comment by ghjm** [comment]
Ok thanks

**Comment by ghjm** [comment]
Hi, can you give an idea when you expect to push the new release?

**Comment by sosodev** [comment]
V1.3.1 was tagged after my comment was posted. You can upgrade to it now. :)

**Comment by ghjm** [comment]
Oh ok, I was looking at releases rather than tags.  Thanks!

**Comment by sosodev** [comment]
Going to close this now. Left it open for a little while in case somebody else had the same question. 😄
