### ISSUE TITLE
Leading 'P' should be required

### ISSUE THREAD

**Issue by jrdouceur** [sosodev/duration#4]
[ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) require a leading 'P' for all values, even when there are no date elements. [This test value](https://github.com/sosodev/duration/blob/main/duration_test.go#L30) should produce an error but does not. The sample in the main README shows a value of "T33.3S" which is not valid; this should be "PT33.3S".

**Comment by sosodev** [comment]
Could you submit a PR for this?

**Comment by sosodev** [comment]
Fixed in the latest release.

**Comment by ccoVeille** [comment]
Fixed with 2cc1d267eb11599d87d75564726f3ac6db2d9cb2 in #5

**Comment by sosodev** [comment]
I've undone the latest release for now because it didn't account for negative durations.
