### ISSUE TITLE
Are you open with contribution?

### ISSUE THREAD

**Issue by ccoVeille** [sosodev/duration#7]
I'm thinking about adding GitHub action for automatic tests, code review …

**Comment by sosodev** [comment]
Absolutely :+1:

**Comment by ccoVeille** [comment]
Great then. Could assign me the ticket then ?

It would be easier for me to find it back

**Comment by sosodev** [comment]
I've added you as a collaborator.

**Comment by ccoVeille** [comment]
Give me a few days, I'm busy with personal thing. I only have a phone right now

Do not hesitate to ping me

**Comment by sosodev** [comment]
Sounds good. No rush.
